imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      ~ #{ fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
      
# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    #form:
        #resources:
            #- '::fields.html.twig'
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
             
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TC\UserBundle\Entity\User
    from_email:
        address:        info@timecrumbs.com
        sender_name:    TimeCrumbs
    registration:
        confirmation:
          enabled : true
          template:   TCUserBundle:Registration:email.txt.twig
        form:
            type: tc_user_registration
            #handler: tc_user.registration.form.handler
            validation_groups:  [TCRegistration]
    resetting:
        email:
            template:   TCUserBundle:Resetting:email.txt.twig
        form:
            validation_groups:  [TCResetPassword]
    profile:
        form:
            type: tc_user_profile
            #handler: tc_user.form.handler.profile
            validation_groups:  [TCProfile]
    service:
        user_manager: tc_user.manager.user
        mailer: tc_user.mailer.default

knp_gaufrette:
    adapters:
        user_adapter:
            local:
                directory: %kernel.root_dir%/../web/img/users

    filesystems:
        user_avatar_fs:
            adapter:    user_adapter
            
vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        user_avatar:
            uri_prefix: /img/users
            upload_destination: user_avatar_fs
            namer: vich_uploader.namer_uniqid

liip_imagine:
    cache_prefix: /cache
    filter_sets:
        80_thumb:
          quality: 100
          filters:
            thumbnail: {size: [80, 80], mode: outbound}
        60_thumb:
            quality: 75
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        30_thumb:
            quality: 75
            filters:
                thumbnail: { size: [30, 30], mode: outbound }
