security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|lib|tpl)/
            security: false

          
        secured_area:
            pattern:    ^/
            form_login:
                provider: fos_userbundle
                use_forward: false
                default_target_path: /            
            anonymous:    true
            logout:
                path:   /logout
                target: /login     
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - path: ^/login$
          role: IS_AUTHENTICATED_ANONYMOUSLY
          requires_channel: https
        - path: ^/register
          role: IS_AUTHENTICATED_ANONYMOUSLY
          requires_channel: https
        - path: ^/resetting
          role: IS_AUTHENTICATED_ANONYMOUSLY
          requires_channel: https
        - path: ^/, role:ROLE_USER
          requires_channel: https
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
